branches:
  only:
    - master

language: node_js
node_js:
  - 12.22

services:
  - docker

script:
  - docker --version
  - docker build -t reverseproxy:latest -f udagram-reverseproxy/Dockerfile udagram-reverseproxy/
  - docker tag udagram-reverseproxy:latest docker12345gp/reverseproxy:latest
  - docker build -t udagram-frontend:latest -f udagram-frontend/Dockerfile udagram-frontend/
  - docker tag udagram-frontend:latest docker12345gp/udagram-frontend:latest
  - docker build -t udagram-api-user:latest -f udagram-api-user/Dockerfile udagram-api-user/
  - docker tag udagram-api-user:latest docker12345gp/udagram-api-user:latest
  - docker build -t udagram-api-feed:latest -f udagram-api-feed/Dockerfile udagram-api-feed/
  - docker tag udagram-api-feed:latest docker12345gp/udagram-api-feed:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push  docker12345gp/reverseproxy
  - docker push  docker12345gp/udagram-frontend
  - docker push  docker12345gp/udagram-api-user
  - docker push  docker12345gp/udagram-api-feed
