language: node_js
node_js:
  - 12.22

services:
  - docker

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build

deploy:
  provider: script
  script: docker_push.sh
  on:
    branch: master
