version: "3"
services:  

  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: docker12345gp/reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: docker12345gp/udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: docker12345gp/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: docker12345gp/udagram-frontend:local